// Gradient stop injection for shape-layer Gradient Fill / Gradient Stroke.
// AE does not expose 'ADBE Vector Grad Colors' to scripting (NO_VALUE through
// AE 26.x), so stops are written via a generated .ffx preset and applyPreset()
// with the target property selected (technique popularized by Google AEUX).
//
// The preset container is a canonical AE 2026-authored G-Fill group preset
// (src/ae/grad-canonical.jsx, generated by tools/gen-grad-template.js). We
// splice freshly generated Gradient Color Data XML into its Utf8 chunk and
// patch the RIFX ancestor chunk sizes by the length delta. Geometry (type,
// start/end, highlight) is set via normal scripting AFTER the preset applies,
// since the preset also carries those properties.

var SVGSPLIT = SVGSPLIT || {};

SVGSPLIT.aegrad = (function () {
  var MAX_STOPS = 32;
  var tempFfxFile = null;

  // Resample gradient stops down to n evenly spaced entries.
  function resampleStops(stops, n) {
    if (stops.length <= n) return stops;
    var out = [];
    for (var i = 0; i < n; i++) {
      var t = i / (n - 1);
      var lo = stops[0];
      var hi = stops[stops.length - 1];
      for (var j = 0; j < stops.length - 1; j++) {
        if (stops[j].offset <= t && stops[j + 1].offset >= t) {
          lo = stops[j];
          hi = stops[j + 1];
          break;
        }
      }
      var span = hi.offset - lo.offset;
      var f = span > 0 ? (t - lo.offset) / span : 0;
      out[out.length] = {
        offset: t,
        color: {
          r: lo.color.r + (hi.color.r - lo.color.r) * f,
          g: lo.color.g + (hi.color.g - lo.color.g) * f,
          b: lo.color.b + (hi.color.b - lo.color.b) * f
        },
        opacity: lo.opacity + (hi.opacity - lo.opacity) * f
      };
    }
    return out;
  }

  function floatXml(v) {
    // match AE's own compact float formatting closely enough
    var s = String(Math.round(v * 100000000) / 100000000);
    return '<float>' + s + '</float>';
  }

  // Generates the Gradient Color Data <prop.map> XML for the given stops,
  // in the exact shape AE 2026 writes (see probe-canonical.ffx).
  function buildStopsXml(stops) {
    var i;
    var alpha = '';
    for (i = 0; i < stops.length; i++) {
      alpha += '<prop.pair>\n<key>Stop-' + i + '</key>\n<prop.list>\n<prop.pair>\n' +
        '<key>Stops Alpha</key>\n<array>\n<array.type><float/></array.type>\n' +
        floatXml(stops[i].offset) + '\n' +
        floatXml(0.5) + '\n' +
        floatXml(stops[i].opacity) + '\n' +
        '</array>\n</prop.pair>\n</prop.list>\n</prop.pair>\n';
    }
    var color = '';
    for (i = 0; i < stops.length; i++) {
      color += '<prop.pair>\n<key>Stop-' + i + '</key>\n<prop.list>\n<prop.pair>\n' +
        '<key>Stops Color</key>\n<array>\n<array.type><float/></array.type>\n' +
        floatXml(stops[i].offset) + '\n' +
        floatXml(0.5) + '\n' +
        floatXml(stops[i].color.r) + '\n' +
        floatXml(stops[i].color.g) + '\n' +
        floatXml(stops[i].color.b) + '\n' +
        '<float>1</float>\n' +
        '</array>\n</prop.pair>\n</prop.list>\n</prop.pair>\n';
    }
    var sizeInt = '<prop.pair>\n<key>Stops Size</key>\n' +
      "<int type='unsigned' size='32'>" + stops.length + '</int>\n</prop.pair>\n';
    return "<prop.map version='4'>\n<prop.list>\n<prop.pair>\n" +
      '<key>Gradient Color Data</key>\n<prop.list>\n' +
      '<prop.pair>\n<key>Alpha Stops</key>\n<prop.list>\n' +
      '<prop.pair>\n<key>Stops List</key>\n<prop.list>\n' + alpha +
      '</prop.list>\n</prop.pair>\n' + sizeInt +
      '</prop.list>\n</prop.pair>\n' +
      '<prop.pair>\n<key>Color Stops</key>\n<prop.list>\n' +
      '<prop.pair>\n<key>Stops List</key>\n<prop.list>\n' + color +
      '</prop.list>\n</prop.pair>\n' + sizeInt +
      '</prop.list>\n</prop.pair>\n' +
      '</prop.list>\n</prop.pair>\n' +
      '<prop.pair>\n<key>Gradient Colors</key>\n<string>1.0</string>\n</prop.pair>\n' +
      '</prop.list>\n</prop.map>';
  }

  function be32(v) {
    return String.fromCharCode((v >>> 24) & 255, (v >>> 16) & 255, (v >>> 8) & 255, v & 255);
  }

  function readBe32(s, off) {
    return s.charCodeAt(off) * 16777216 + s.charCodeAt(off + 1) * 65536 +
      s.charCodeAt(off + 2) * 256 + s.charCodeAt(off + 3);
  }

  // Builds the complete .ffx byte string for the given stops.
  function buildFfx(stops) {
    var base = SVGSPLIT.gradCanonical;
    var xml = buildStopsXml(stops);
    // keep parity with the canonical XML so RIFF chunk padding stays aligned
    if ((xml.length - base.xmlLength) % 2 !== 0) xml += '\n';
    var delta = xml.length - base.xmlLength;
    var head = base.head;

    if (delta !== 0) {
      // find the ancestor chunk chain containing the XML (walk over head bytes;
      // canonical sizes are correct, so the walk is reliable)
      var target = head.length;
      var sizeOffsets = [];
      function walk(off, end) {
        while (off + 8 <= end) {
          var id = head.substring(off, off + 4);
          if (off + 8 > head.length) return;
          var size = readBe32(head, off + 4);
          var dataStart = off + 8;
          var dataEnd = dataStart + size;
          if (target >= dataStart && target < dataEnd) {
            sizeOffsets[sizeOffsets.length] = off + 4;
            if (id === 'RIFX' || id === 'LIST') walk(dataStart + 4, dataEnd);
            return;
          }
          off = dataEnd + (size % 2);
        }
      }
      // Utf8 leaf: its header sits immediately before the XML
      walk(0, head.length + 1);
      // also patch the Utf8 chunk itself (last 'Utf8' id before XML)
      var utf8Off = head.lastIndexOf('Utf8');
      if (utf8Off !== -1) {
        var found = false;
        for (var k = 0; k < sizeOffsets.length; k++) {
          if (sizeOffsets[k] === utf8Off + 4) found = true;
        }
        if (!found) sizeOffsets[sizeOffsets.length] = utf8Off + 4;
      }
      for (var i = 0; i < sizeOffsets.length; i++) {
        var so = sizeOffsets[i];
        head = head.substring(0, so) + be32(readBe32(head, so) + delta) + head.substring(so + 4);
      }
    }
    return head + xml + base.tail;
  }

  function writeFfx(stops) {
    if (stops.length < 2) return null;
    if (stops.length > MAX_STOPS) stops = resampleStops(stops, MAX_STOPS);
    var data = buildFfx(stops);
    var file = new File(Folder.temp.fsName + '/svg-splitter-grad.ffx');
    file.encoding = 'BINARY';
    if (!file.open('w')) return null;
    file.write(data);
    file.close();
    tempFfxFile = file;
    return file;
  }

  function deselectAll(comp) {
    var sel = comp.selectedProperties;
    for (var i = sel.length - 1; i >= 0; i--) {
      sel[i].selected = false;
    }
    var selLayers = comp.selectedLayers;
    for (var j = selLayers.length - 1; j >= 0; j--) {
      selLayers[j].selected = false;
    }
  }

  // Applies gradient stops + geometry to a freshly created G-Fill/G-Stroke
  // property. Applying the preset REPLACES the property (the old reference
  // becomes invalid), so we re-resolve it from the parent group afterwards.
  // Returns { applied: bool, prop: Property } - prop is the live property to
  // keep using; when applied is false the caller should fall back to solid.
  // paint: scene gradient paint {kind, stops, start, end, hilite}
  // toLayerSpace: function([x,y]) -> [x,y] mapping comp coords to layer coords.
  function apply(comp, layer, gradProp, paint, toLayerSpace, warn) {
    var applied = false;
    if (paint.stops.length > MAX_STOPS) {
      warn('gradient has ' + paint.stops.length + ' stops; resampled to ' + MAX_STOPS);
    }

    var parent = gradProp.parentProperty;
    var propIndex = gradProp.propertyIndex;
    var matchName = gradProp.matchName;

    var ffx = null;
    try {
      ffx = writeFfx(paint.stops);
    } catch (eWrite) {
      ffx = null;
    }
    if (ffx) {
      try {
        deselectAll(comp);
        gradProp.selected = true;
        layer.applyPreset(ffx);
        layer.selected = false;
        applied = true;
      } catch (eApply) {
        warn('gradient preset failed to apply (' + eApply.toString() + '); using first-stop solid');
      }
    } else {
      warn('could not write gradient preset (enable "Allow Scripts to Write Files and Access Network" in Preferences > Scripting & Expressions); using first-stop solid');
    }

    // Re-resolve: the preset apply may have replaced the property.
    var live = null;
    try {
      var candidate = propIndex <= parent.numProperties ? parent.property(propIndex) : null;
      if (candidate !== null && candidate.matchName === matchName) {
        live = candidate;
      } else {
        for (var pi = parent.numProperties; pi >= 1; pi--) {
          if (parent.property(pi).matchName === matchName) {
            live = parent.property(pi);
            break;
          }
        }
      }
    } catch (eResolve) {
      live = null;
    }
    if (live === null) {
      warn('gradient property lost after preset apply; recreating');
      live = parent.addProperty(matchName);
      applied = false;
    }

    // Geometry after the preset so our values win.
    var start = toLayerSpace(paint.start);
    var end = toLayerSpace(paint.end);
    live.property('ADBE Vector Grad Type').setValue(paint.kind === 'radial' ? 2 : 1);
    live.property('ADBE Vector Grad Start Pt').setValue(start);
    live.property('ADBE Vector Grad End Pt').setValue(end);
    if (paint.kind === 'radial' && paint.hilite) {
      try {
        live.property('ADBE Vector Grad HiLite Length').setValue(paint.hilite.length * 100);
        live.property('ADBE Vector Grad HiLite Angle').setValue(paint.hilite.angleDeg);
      } catch (eHilite) {
        warn('radial focal point not applied: ' + eHilite.toString());
      }
    }
    return { applied: applied, prop: live };
  }

  function cleanup() {
    if (tempFfxFile !== null) {
      try {
        tempFfxFile.remove();
      } catch (e) {
        // best effort
      }
      tempFfxFile = null;
    }
  }

  return {
    apply: apply,
    cleanup: cleanup,
    resampleStops: resampleStops,
    buildStopsXml: buildStopsXml,
    buildFfx: buildFfx
  };
})();
